### ISSUE TITLE
[Vault] vault has been updated to 0.7.3

### ISSUE THREAD

**Issue by nergdron** [manala/debian-packages#15]
Code here builds a package for 0.7.0, but the latest stable release is 0.7.3:

https://releases.hashicorp.com/vault/0.7.3/vault_0.7.3_linux_amd64.zip

**Comment by nervo** [comment]
See https://github.com/manala/debian-packages/pull/53 and https://github.com/manala/debian-packages/pull/54

**Comment by nervo** [comment]
Closed by #53 and #54
